// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateItem(arg1) {
  return window['go']['backend']['App']['CreateItem'](arg1);
}

export function GetItems() {
  return window['go']['backend']['App']['GetItems']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}
