// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function CreateItem(arg1:string):Promise<void>;

export function GetItems():Promise<Array<internal.Item>>;

export function Greet(arg1:string):Promise<string>;
