name: Wails Windows Build

# on:
#   push:
#     tags:
#       - '*'
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Increase memory limit to prevent OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go get -u github.com/mattn/go-sqlite3
          go get -u github.com/go-sql-driver/mysql
          go get -u github.com/lib/pq

      - name: Build Wails application
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: 'My Desktop App'
          build-platform: 'windows/amd64'
          package: false
          go-version: '1.21'

      - name: Ensure SQLite DLL is included
        run: |
          mkdir -p .\build\bin\MyApp
          copy C:\path\to\sqlite3.dll .\build\bin\MyApp\

      - name: List build directory
        run: |
          dir .\build\bin\

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: ./build/bin/my-desktop-app-amd64-installer.exe
